### ISSUE TITLE
Error: Web3ProviderEngine does not support synchronous requests.

### ISSUE THREAD

**Issue by lsankar4033** [hussy-io/truffle-ledger-provider#11]
I'm running into the following issue when attempting to run migrations:

```
$ truffle migrate --reset --network mainnet

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Migrations dry-run (simulation)
===============================
> Network name:    'mainnet-fork'
> Network id:      1
> Block gas limit: 0x7a7c7e


1_initial_migrations.js
=======================

   Deploying 'Migrations'
   ----------------------
   > block number:        7843026
   > block timestamp:     1558978295
   > account:             [REDACTED]
   > balance:             [REDACTED]
   > gas used:            262462
   > gas price:           5 gwei
   > value sent:          0 ETH
   > total cost:          0.00131231 ETH

   -------------------------------------
   > Total cost:          0.00131231 ETH


Summary
=======
> Total deployments:   1
> Final cost:          0.00131231 ETH

Error: Error: Web3ProviderEngine does not support synchronous requests.
    at Object.run (/Users/lsankar/.asdf/installs/nodejs/9.11.2/.npm/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:84:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

The migration I'm running is quite straightforward:

```
var Migrations = artifacts.require("./Migrations.sol");

module.exports = function(deployer) {
  deployer.deploy(Migrations);
};
```

and here's my truffle-config:

```
// for mainnet
require('babel-polyfill');
const LedgerWalletProvider = require('truffle-ledger-provider');

module.exports = {
  networks: {
    mainnet: {
      network_id: 1,
      provider: () => new LedgerWalletProvider({} , [INFURA_API_URL]),
      gas: 4600000, // Gas limit used for deploys
      gasPrice: 5000000000 // 5 gwei
    }
  }
}
```

Has anyone run into this issue?

**Comment by kartojal** [comment]
Did someone find a solution or workaround for this issue?

**Comment by NotRealAI** [comment]
@kartojal @lsankar4033 use https://github.com/UMAprotocol/truffle-ledger-provider
