### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by CorentinGC** [hussy-io/truffle-ledger-provider#9]
OS : OS X 10.14.12

Hi ! 

I just tried to deploy using the default configuration: 
```
const LedgerWalletProvider = require('truffle-ledger-provider');

const INFURA_APIKEY = process.env.INFRURA_PROJECT_ID; // set your Infura API key
const ledgerOptions = {
  networkId: 3, // ropsten
  path: "44'/60'/0'/0", // ledger default derivation path
  askConfirm: false,
  accountsLength: 1,
  accountsOffset: 0
};

module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 8545,
      network_id: '*' // Match any network id
    },
    ropsten: {
      provider: new LedgerWalletProvider(ledgerOptions, `https://ropsten.infura.io/${INFURA_APIKEY}`),
      network_id: 3,
      gas: 4600000
    }
  }
};
```
Then I launched deploy with:
```
$ make deploy NETWORK=ropsten
```

And I got this error  : 
```
truffle migrate --network ropsten -f 1 --to 2
ReferenceError: regeneratorRuntime is not defined
    at /Users/username/project_path/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:355:50
    at /Users/username/project_path/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:394:6
    at Object.<anonymous> (/Users/username/project_path/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:398:2)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/username/project_path/node_modules/truffle-ledger-provider/index.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/username/project_path/truffle-config.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.Config.load (/Users/username/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/Users/username/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
Truffle v5.0.1 (core: 5.0.1)
Node v10.2.1
make: *** [deploy] Error 1
```

Thank you

**Comment by savitar-dev** [comment]
Ok, I fixed the problem with babel polyfill ( cf : https://babeljs.io/docs/en/babel-polyfill )

1. npm install --save @babel/polyfill
2. Add this to truffle-config.js : 
`require("@babel/polyfill");
`

**Comment by CorentinGC** [comment]
Ok, I fixed the problem with babel polyfill ( cf : https://babeljs.io/docs/en/babel-polyfill )

1. npm install --save @babel/polyfill
2. Add this to truffle-config.js : 
`require("@babel/polyfill");
`
